version: 2
jobs:
  build:
    working_directory: ~/notify-driver-api
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:latest
        environment:
          MONGODB_DATABASE: "db_notifydriver"
      - image: rabbitmq:latest
        environment:
          RABBITMQ_DEFAULT_USER: "notifydriver"
          RABBITMQ_DEFAULT_PASS: "writeread"
          RABBITMQ_DEFAULT_VHOST: "/notifydriver"
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test-cover
          command: npm run test
      - run:
          name: test
          command: npm run codecov